spring:
  ### profiles
  profiles:
    include:
      - oauth
      - aws

  ### Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3606/modongmun?serverTimezone=Asia/Seoul
    username: modongmun
    password: modongmun1234!

  ### JPA
  jpa:
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl_auto: update


