cloud:
  aws:
    credentials:
      accessKey: AKIAQ6Z7ET3L4EQCJ3TR
      secretKey: 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
    s3:
      bucket: modongmun
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  ### profiles
  profiles:
    include: oauth

  ### Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3606/modongmun?serverTimezone=Asia/Seoul
    username: ssafy
    password: 1234

  ### JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl_auto: update